global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: be-01
    static_configs:
      - targets: ['be-01:3100']
    metrics_path: /metrics

  - job_name: gw-01
    static_configs:
      - targets: ['gw-01:3200']
    metrics_path: /metrics
