apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/platform/networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: puni-platform
  kubeConfig:
    secretRef:
      name: workers-production-kubeconfig
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: target
  wait: true
  timeout: 10m
