plugin: hetzner.hcloud.hcloud
strict: true
cache: false
label_selector: puni-fleet=puni,puni-cluster=platform
connect_with: private_ipv4
compose:
  puni_cluster: hcloud_labels['puni-cluster']
  puni_instance_id: hcloud_id | string
  puni_private_ipv4: hcloud_private_ipv4
