apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../eck
  - ../elastic/local
  - ../elastic/settings
  - ../kibana
  - ../prometheus
  - ../otel
  - telemetry.yaml
  - otlp-ingress.yaml
  - receiver.yaml
