import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { format, type Options } from 'prettier';

/** `--check` compares, `--write` regenerates. Nothing else is a mode. */
type Mode = '--check' | '--write';

/** Existing source forms differ in prompts/examples; preserve both, without copied templates. */
const workflows = [
  ['apply', 'apply-change', 'Apply', ['workflow', 'artifacts', 'experimental']],
  ['archive', 'archive-change', 'Archive', ['workflow', 'archive', 'experimental']],
  [
    'bulk-archive',
    'bulk-archive-change',
    'Bulk Archive',
    ['workflow', 'archive', 'experimental', 'bulk'],
  ],
  ['continue', 'continue-change', 'Continue', ['workflow', 'artifacts', 'experimental']],
  ['explore', 'explore', 'Explore', ['workflow', 'explore', 'experimental', 'thinking']],
  ['ff', 'ff-change', 'Fast Forward', ['workflow', 'artifacts', 'experimental']],
  ['new', 'new-change', 'New', ['workflow', 'artifacts', 'experimental']],
  ['onboard', 'onboard', 'Onboard', ['workflow', 'onboarding', 'tutorial', 'learning']],
  ['sync', 'sync-specs', 'Sync', ['workflow', 'specs', 'experimental']],
  ['verify', 'verify-change', 'Verify', ['workflow', 'verify', 'experimental']],
] as const;

/** The skill owning the archive-input policy; it receives no marker naming itself. */
const archiveOwner = '.agents/skills/openspec-archive-change/SKILL.md';
/** The skill owning the fast-forward required-artifact loop. */
const ffOwner = '.agents/skills/openspec-ff-change/SKILL.md';

/**
 * Twenty canonical sources are also outputs, so a human can open a copy and edit
 * it. This line, first thing under the frontmatter, says which file to edit
 * instead. It is stripped on read and re-added on write, so it is idempotent.
 *
 * Proof: with markGenerated returning the text unchanged, 'a generated copy
 * names the file a human should edit instead' failed on `Expected to contain:
 * "<!-- Generated by tool-workflows from .agents/skills/openspec-ff-change/SKILL.md;
 * edit that file, not this copy. -->"`.
 */
function generatedMarker(owner: string): string {
  return `<!-- Generated by tool-workflows from ${owner}; edit that file, not this copy. -->`;
}

const markerLine = /^<!-- Generated by tool-workflows from [^\n]*-->\n\n?/gm;

/**
 * Frontmatter must stay first: a marker above it would be read as the body, so
 * the caller passes the length of the header it already parsed or built. There
 * is no re-parse here, and so no guard whose removal nothing could observe.
 */
function markGenerated(text: string, owner: string | undefined, headerLength: number): string {
  if (owner === undefined) return text;
  return `${text.slice(0, headerLength)}\n${generatedMarker(owner)}\n${text.slice(headerLength)}`;
}

/** Throws on unreadable/malformed source; command bodies cannot silently become empty. */
function readSource(
  root: string,
  pathname: string,
): { text: string; description: string; headerLength: number } {
  // Proof: workflows.test.ts removes/chmods canonical sources; the actual CLI
  // exits 1 naming the path (ENOENT/EACCES), for both --check and --write.
  // The marker is stripped here and re-added on write, so a source that is also
  // an output does not accumulate one per run.
  // Proof: with this .replace removed, 'a generated copy names the file a human
  // should edit instead' failed at its re-check line on `Expected: 0 /
  // Received: 1` — the second --write had stacked a second marker.
  const text = readFileSync(join(root, pathname), 'utf8').replace(markerLine, '');
  const matched = /^---\n([\s\S]*?)\n---\n([\s\S]+)$/.exec(text);
  // Proof: 'a damaged source wrapper cannot silently erase a command' supplies
  // a wrapper without frontmatter; the CLI exits 1 and names that source.
  if (!matched?.[1] || !matched[2]) throw new Error(`Malformed workflow source: ${pathname}`);
  const header: unknown = Bun.YAML.parse(matched[1]);
  // Proof: workflows.test.ts replaces description with missing-description;
  // the CLI exits 1 naming the source and leaves the probe variant unchanged.
  if (
    typeof header !== 'object' ||
    header === null ||
    !('description' in header) ||
    typeof header.description !== 'string'
  ) {
    throw new Error(`Missing workflow description: ${pathname}`);
  }
  return {
    text,
    description: header.description,
    headerLength: text.length - matched[2].length,
  };
}

/**
 * The repository's own prettier settings, so generated files match `nx format:check`.
 * A second hardcoded copy here would drift from `.prettierrc.json` in silence.
 */
function readFormatOptions(root: string): Options {
  // Proof: hardcoding `{ singleQuote: true, printWidth: 100 }` here instead of
  // reading the file left 'the repository prettier configuration decides the
  // generated formatting' on `Expected: 1 / Received: 0`, and the absent,
  // unreadable and malformed cases on `Expected to contain: ".prettierrc.json"
  // / Received: "Error: Workflow drift: .claude/commands/opsx/archive.md ..."`.
  const parsed: unknown = JSON.parse(readFileSync(join(root, '.prettierrc.json'), 'utf8'));
  // Proof: with this guard deleted, 'a malformed .prettierrc.json stops
  // generation' (which writes `[]`) failed on `Expected to contain:
  // ".prettierrc.json" / Received: "Error: Workflow drift:
  // .agents/skills/openspec-apply-change/SKILL.md ..."` — the empty array
  // spread away silently and the run reported drift instead of the bad config.
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed))
    throw new Error(`Malformed prettier configuration: ${join(root, '.prettierrc.json')}`);
  // Boundary cast: the shape beyond "a JSON object" is prettier's own contract,
  // and prettier throws on an option value it does not accept.
  const configured = parsed as Options;
  // Plugin specifiers resolve from this tool's own installation rather than from
  // `root`: a disposable fixture has no node_modules, and prettier resolves a
  // bare specifier against the process. Bun.resolveSync throws on an absent one.
  const plugins = (configured.plugins ?? []).map((plugin) =>
    typeof plugin === 'string' ? Bun.resolveSync(plugin, import.meta.dir) : plugin,
  );
  return { ...configured, plugins, parser: 'markdown' };
}

/** A single skill owns each shared policy block; other installed forms receive it here. */
function replacePolicy(
  text: string,
  policy: RegExp,
  replacement: string,
  pathname: string,
): string {
  // Proof: workflows.test.ts removes the bulk archive policy heading; the CLI
  // exits 1 naming that source and leaves the probe variant unchanged.
  if (!policy.test(text)) throw new Error(`Missing shared policy in ${pathname}`);
  return text.replace(policy, () => replacement);
}

function renderClaude(text: string): string {
  for (const [command, skill] of workflows)
    text = text.replaceAll(`/openspec-${skill}`, `/opsx:${command}`);
  return text.replaceAll('/openspec-propose', '/opsx:propose');
}

/** Every file under a directory this generator owns, as repository-relative paths. */
function listFiles(root: string, directory: string): string[] {
  const found: string[] = [];
  for (const name of readdirSync(join(root, directory))) {
    const pathname = `${directory}/${name}`;
    if (statSync(join(root, pathname)).isDirectory()) found.push(...listFiles(root, pathname));
    else found.push(pathname);
  }
  return found;
}

/** Read every source before writing; check reads all 40 actual installed paths without Nx caching.
 * Maintenance contract: docs/2026-09-06-openspec-upgrade.md.
 */
async function generateWorkflows(mode: Mode, root: string): Promise<void> {
  const formatOptions = readFormatOptions(root);
  const sources = workflows.map(([command, skill, title, tags]) => {
    const skillPath = `.agents/skills/openspec-${skill}/SKILL.md`;
    const commandPath = `.agents/skills/source-command-opsx-${command}/SKILL.md`;
    return {
      command,
      title,
      tags,
      skillPath,
      commandPath,
      skill: readSource(root, skillPath),
      wrapper: readSource(root, commandPath),
    };
  });
  const supported = new Set(sources.flatMap((source) => [source.skillPath, source.commandPath]));
  // Proof: the unrecognized-source CLI test exited 0 without this inventory check
  // (expected 1); adding openspec-unrecognized is now refused before generation.
  for (const name of readdirSync(join(root, '.agents/skills'))) {
    const pathname = `.agents/skills/${name}/SKILL.md`;
    if (
      (name.startsWith('openspec-') || name.startsWith('source-command-opsx-')) &&
      !supported.has(pathname)
    ) {
      throw new Error(`Unsupported workflow source: ${pathname}`);
    }
  }
  const archivePattern = / {3}\*\*Load current archive inputs[\s\S]*?(?=\n\d+\. \*\*)/;
  const ffPattern = /4\. \*\*Create every artifact[\s\S]*?(?=5\. \*\*Show final status)/;
  function readPolicy(pathname: string, pattern: RegExp): string {
    const policy = pattern.exec(readSource(root, pathname).text)?.[0];
    // Proof: workflows.test.ts removes the canonical archive policy heading;
    // the CLI exits 1 naming that source before changing the probe variant.
    if (!policy) throw new Error(`Missing canonical policy in ${pathname}`);
    return policy;
  }
  const archivePolicy = readPolicy(archiveOwner, archivePattern);
  const ffPolicy = readPolicy(ffOwner, ffPattern);
  const outputs = new Map<string, string>();
  for (const source of sources) {
    let skillText = source.skill.text;
    let wrapperText = source.wrapper.text;
    let skillOwner: string | undefined;
    let wrapperOwner: string | undefined;
    if (source.command === 'archive' || source.command === 'bulk-archive') {
      skillText = replacePolicy(skillText, archivePattern, archivePolicy, source.skillPath);
      if (source.skillPath !== archiveOwner) skillOwner = archiveOwner;
      wrapperText = replacePolicy(wrapperText, archivePattern, archivePolicy, source.commandPath);
      wrapperOwner = archiveOwner;
    }
    if (source.command === 'ff') {
      wrapperText = replacePolicy(wrapperText, ffPattern, ffPolicy, source.commandPath);
      wrapperOwner = ffOwner;
    }
    const parts = wrapperText.split('## Command Template\n');
    // Proof: with this branch deleted, 'a duplicated command template heading
    // stops generation before writes' failed on `Expected: 1 / Received: 0`;
    // the zero-heading case is covered by 'damaged source boundary
    // ## Command Template in .agents/skills/source-command-opsx-ff/SKILL.md'.
    if (parts.length !== 2)
      throw new Error(
        `Expected one '## Command Template' heading in ${source.commandPath}; found ${String(parts.length - 1)}`,
      );
    const commandBody = parts[1];
    // Proof: an emptied template body leaves nothing to install; the CLI exits 1
    // naming the wrapper and leaves the probe variant unchanged.
    if (!commandBody?.trim()) throw new Error(`Empty command template: ${source.commandPath}`);
    const commandHeader = `---\nname: ${JSON.stringify(`OPSX: ${source.title}`)}\ndescription: ${JSON.stringify(source.wrapper.description)}\nallowed-tools: Bash(openspec:*)\ncategory: Workflow\ntags: ${JSON.stringify(source.tags)}\n---\n`;
    const claudeSkillPath = source.skillPath.replace('.agents/', '.claude/');
    const claudeCommandPath = `.claude/commands/opsx/${source.command}.md`;
    const skillHeader = source.skill.headerLength;
    const wrapperHeader = source.wrapper.headerLength;
    outputs.set(source.skillPath, markGenerated(skillText, skillOwner, skillHeader));
    outputs.set(source.commandPath, markGenerated(wrapperText, wrapperOwner, wrapperHeader));
    // The header is rendered too, so its length is measured after rendering
    // rather than assumed unchanged by the invocation rewrite.
    outputs.set(
      claudeSkillPath,
      markGenerated(
        renderClaude(skillText),
        source.skillPath,
        renderClaude(skillText.slice(0, skillHeader)).length,
      ),
    );
    outputs.set(
      claudeCommandPath,
      markGenerated(commandHeader + commandBody, source.commandPath, commandHeader.length),
    );
  }
  // A directory this generator owns holds nothing it did not compute. Without
  // this an added file was invisible to --check: it compares the computed set
  // against disk and never looks the other way.
  // Proof: with this loop replaced by `void ownedRoots;`, all three 'an added
  // file under a generated output root is refused' cases failed on
  // `Expected: 1 / Received: 0` — .claude/commands/opsx/stray.md,
  // .claude/skills/openspec-explore/REFERENCE.md and
  // .agents/skills/source-command-opsx-new/NOTES.md each passed unseen.
  const ownedRoots = [
    ...readdirSync(join(root, '.agents/skills'))
      .filter((name) => name.startsWith('openspec-') || name.startsWith('source-command-opsx-'))
      .map((name) => `.agents/skills/${name}`),
    ...readdirSync(join(root, '.claude/skills'))
      .filter((name) => name.startsWith('openspec-'))
      .map((name) => `.claude/skills/${name}`),
    '.claude/commands/opsx',
  ];
  for (const owned of ownedRoots)
    for (const pathname of listFiles(root, owned))
      if (!outputs.has(pathname))
        throw new Error(
          `Untracked file under a generated output root: ${pathname}; delete it or add its source`,
        );
  const rendered = await Promise.all(
    [...outputs].map(
      async ([pathname, text]) => [pathname, await format(text, formatOptions)] as const,
    ),
  );
  for (const [pathname, text] of rendered) {
    const absolute = join(root, pathname);
    if (mode === '--check') {
      // Proof: removing this comparison made the divergent-command CLI test fail:
      // expected exit 1, received 0. Deleted/chmod-000 variants produce ENOENT/EACCES.
      if (readFileSync(absolute, 'utf8') !== text)
        throw new Error(`Workflow drift: ${pathname}; run bunx nx run tool-workflows:generate`);
    } else {
      mkdirSync(dirname(absolute), { recursive: true });
      writeFileSync(absolute, text);
    }
  }
  process.stdout.write(
    `${mode === '--check' ? 'Checked' : 'Generated'} ${String(outputs.size)} workflow variants\n`,
  );
}

/**
 * The argv boundary is where an unvalidated string stops being a string.
 *
 * Proof: passing a literal '--bogus' straight to generateWorkflows failed
 * `bunx tsc --build --force tools/tool-workflows/tsconfig.json` with
 * `error TS2345: Argument of type '"--bogus"' is not assignable to parameter of
 * type 'Mode'.` — the parameter was `string` before this change and compiled.
 */
function parseMode(argument: string | undefined): Mode {
  // Proof: 'unsupported CLI arguments fail without writing' passes --unknown;
  // the actual CLI exits 1.
  if (argument !== '--check' && argument !== '--write')
    throw new Error('Usage: generate.ts <--check|--write> [repository]');
  return argument;
}

const [requested, directory, ...extra] = process.argv.slice(2);
try {
  if (extra.length > 0) throw new Error('Usage: generate.ts <--check|--write> [repository]');
  await generateWorkflows(parseMode(requested), resolve(directory ?? process.cwd()));
} catch (failure) {
  // Exit 1 is this CLI's refusal contract, asserted by every negative in
  // workflows.test.ts and by the Nx `check` target. Bun's own code for an
  // uncaught throw is not 1 once a prettier plugin has been imported: the
  // drift and EACCES cases were observed exiting 7. Nothing is swallowed —
  // the stack is written before the exit.
  process.stderr.write(
    `${failure instanceof Error ? (failure.stack ?? failure.message) : String(failure)}\n`,
  );
  process.exit(1);
}
